name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Build CSS
        run: npm run build
      - name: Check dist up-to-date
        run: |
          git diff --exit-code dist
