name: Refresh Dev Trading Card
on:
  schedule:
    - cron: '0 * * * *'    # every hour
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Fetch contributions & languages
        id: stats
        run: |
          USER="your-username"
          contribs=$(curl -s "https://api.github.com/users/$USER/events" \
            | jq '[.[] | select(.type=="PushEvent")] | length')
          langs=$(curl -s "https://api.github.com/repos/$USER?per_page=1" \
            | jq '.languages_url' -r \
            | xargs curl -s \
            | jq 'to_entries | sort_by(-.value) | .[:4]')
          echo "::set-output name=contribs::$contribs"
          echo "::set-output name=langs::$langs"
      - name: Generate trading card snippet
        run: |
          mkdir -p .github/dev-card
          SKILLS=$(jq -r 'to_entries[] | "| \(.key) | \(.value)/10 |"' .github/dev-card/skills.json)
          LANG_BADGES=$(echo "${{ steps.stats.outputs.langs }}" \
            | jq -r '.[] | "[![\(.key)](\(.value | tostring)?style=flat&logo=\(.key))](https://github.com/your-username?tab=repositories&language=\(.key))"')
          cat > .github/dev-card/card.md <<EOF
